#!/bin/bash
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install -y ros-kinetic-dbw-mkz-msgs
cd /home/workspace/CarND-Capstone/ros
rosdep install --from-paths src --ignore-src --rosdistro=kinetic -y
sudo apt-get install ros-kinetic-image-view
git config --global user.email "gvpsha@gmail.com"
git config --global user.name "gvp-study"


